# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
  # Ensure ShazamKit compatibility

prepare_react_native_project!

# React Native 0.73 points boost to a JFrog URL that can return a bad archive/checksum.
# Patch the podspec to use the stable Boost mirror before dependency resolution.
boost_podspec = File.join(__dir__, '..', 'node_modules', 'react-native', 'third-party-podspecs', 'boost.podspec')
boost_old_url = 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2'
boost_new_url = 'https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.bz2'
if File.exist?(boost_podspec)
  boost_contents = File.read(boost_podspec)
  if boost_contents.include?(boost_old_url)
    File.write(boost_podspec, boost_contents.gsub(boost_old_url, boost_new_url))
    Pod::UI.puts('Patched boost podspec URL to archives.boost.io'.yellow)
  end
end

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Resonate' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ResonateTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    strip_ld_classic = lambda do |build_settings|
      ldflags = build_settings['OTHER_LDFLAGS']
      if ldflags.is_a?(Array)
        build_settings['OTHER_LDFLAGS'] = ldflags.reject { |flag| flag.to_s == '-ld_classic' }
      elsif ldflags.to_s.include?('-ld_classic')
        build_settings['OTHER_LDFLAGS'] = ldflags.to_s.split(/\s+/).reject { |flag| flag == '-ld_classic' }.join(' ')
      end
    end

    strip_duplicate_libcpp = lambda do |build_settings|
      ldflags = build_settings['OTHER_LDFLAGS']
      if ldflags.is_a?(Array)
        build_settings['OTHER_LDFLAGS'] = ldflags.reject { |flag| flag.to_s == '-lc++' }
      elsif ldflags.to_s.include?('-lc++')
        build_settings['OTHER_LDFLAGS'] = ldflags.to_s.split(/\s+/).reject { |flag| flag == '-lc++' }.join(' ')
      end
    end

    socketrocket_runloop_thread = File.join(
      installer.sandbox.root.to_s,
      'SocketRocket',
      'SocketRocket',
      'Internal',
      'RunLoop',
      'SRRunLoopThread.m'
    )
    if File.exist?(socketrocket_runloop_thread)
      source = File.read(socketrocket_runloop_thread)
      original = "        thread.name = @\"com.facebook.SocketRocket.NetworkThread\";\n        [thread start];"
      patched = "        thread.name = @\"com.facebook.SocketRocket.NetworkThread\";\n        thread.qualityOfService = NSQualityOfServiceUserInteractive;\n        [thread start];"
      if source.include?(original) && !source.include?('thread.qualityOfService = NSQualityOfServiceUserInteractive;')
        File.write(socketrocket_runloop_thread, source.sub(original, patched))
      end
    end

    # Xcode's C++ mode can reject '$' in identifiers used by RN codegen output.
    # Allow it for all Pods so generated EventEmitters.cpp builds cleanly.
    installer.pods_project.build_configurations.each do |config|
      strip_ld_classic.call(config.build_settings)
      strip_duplicate_libcpp.call(config.build_settings)
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        flags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
        if flags.nil?
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -fdollars-in-identifiers'
        elsif flags.is_a?(Array)
          unless flags.any? { |f| f.to_s.include?('fdollars-in-identifiers') }
            flags << '-fdollars-in-identifiers'
          end
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags
        else
          unless flags.to_s.include?('fdollars-in-identifiers')
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{flags} -fdollars-in-identifiers"
          end
        end

        strip_ld_classic.call(config.build_settings)
        strip_duplicate_libcpp.call(config.build_settings)
      end
    end

    installer.aggregate_targets.map(&:user_project).uniq.each do |project|
      project.build_configurations.each do |config|
        strip_ld_classic.call(config.build_settings)
        strip_duplicate_libcpp.call(config.build_settings)
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end

      project.targets.each do |target|
        target.build_configurations.each do |config|
          strip_ld_classic.call(config.build_settings)
          strip_duplicate_libcpp.call(config.build_settings)
          if target.name == 'Resonate'
            config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
          end
        end
      end

      project.save
    end
  end
end
